name: CloseIssues
on: [issues, pull_request]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues that did not follow issue template
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "@${issue.user.login} Your issue was closed becuase it was a url. The redirect link will still work (at http://url.neumatic.ml/[issue_id]). If you have any actual issues with the repo, do not add a url to them, as they will be closed. Thank you!"
        issue-pattern: "http"
